# Generated by Django 4.1.1 on 2022-09-25 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Database', '0003_alter_grant_currency_alter_grant_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main_Database.activitydetail')),
            ],
        ),
        migrations.AlterField(
            model_name='participant',
            name='activity',
            field=models.ForeignKey(limit_choices_to={'name': True}, on_delete=django.db.models.deletion.CASCADE, to='Main_Database.activity_detail'),
        ),
    ]
