# Generated by Django 4.1.1 on 2022-09-25 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Database', '0004_activity_detail_alter_participant_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main_Database.activity_detail'),
        ),
    ]
