# Generated by Django 4.1.1 on 2022-09-25 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Database', '0005_alter_participant_activity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity_Detail',
            new_name='AddParticipant',
        ),
    ]
