# Generated by Django 4.1.1 on 2022-09-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Database', '0006_rename_activity_detail_addparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='addparticipant',
            name='total_activity',
            field=models.IntegerField(default=5),
        ),
    ]
