# Generated by Django 4.1.1 on 2022-09-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Database', '0007_addparticipant_total_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addparticipant',
            name='total_activity',
            field=models.IntegerField(default=50),
        ),
    ]
