# Generated by Django 4.1.1 on 2022-09-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Database', '0009_question_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_one', models.CharField(blank=True, max_length=100, null=True, verbose_name='Option One')),
                ('option_two', models.CharField(blank=True, max_length=100, null=True, verbose_name='Option Two')),
                ('option_three', models.CharField(blank=True, max_length=100, null=True, verbose_name='Option Three')),
                ('option_four', models.CharField(blank=True, max_length=100, null=True, verbose_name='Option Four')),
                ('option_five', models.CharField(blank=True, max_length=100, null=True, verbose_name='Option Five')),
                ('option_six', models.CharField(blank=True, max_length=100, null=True, verbose_name='Option Six')),
                ('option_one_count', models.IntegerField(default=0)),
                ('option_two_count', models.IntegerField(default=0)),
                ('option_three_count', models.IntegerField(default=0)),
                ('option_four_count', models.IntegerField(default=0)),
                ('option_five_count', models.IntegerField(default=0)),
                ('option_six_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
