# Generated by Django 4.1.1 on 2022-09-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Database', '0010_poll_delete_option_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='activity',
            field=models.CharField(choices=[('Activity X', 'Activity X'), ('Activity Y', 'Activity Y'), ('Activity Z', 'Activity Z'), ('Activity W', 'Activity W')], default='Activity X', max_length=100, verbose_name='Choose Activity'),
        ),
        migrations.AddField(
            model_name='poll',
            name='thematic',
            field=models.CharField(choices=[('SRHR', 'SRHR'), ('HIV/TB', 'HIV/TB'), ('WLPR', 'WLPR'), ('SILU', 'SILU'), ('H&G', 'H&G')], default='SRHR', max_length=100, verbose_name='Choose Thematic'),
        ),
    ]
